ResourceLocator files added
coveo/samples pull request #7
Opened 2017-03-07 15:43 UTC by wnijmeijer

2017-03-07 16:26 UTC, francoislg commented
Do you want Code Reviews? :)

2017-03-08 06:54 UTC, wnijmeijer commented
No

2017-03-08 06:55 UTC, wnijmeijer commented
Gauthier and JF Cloutier already checked it

2017-03-08 19:55 UTC, francoislg requested changes

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/Extension.py
> +    #Field to store the availability in
There are many comments like this that are unfinished.

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/Extension.py
> +    dateEndP2=Date+datetime.timedelta(days=90+currenthours)
4 unused variables here.

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/Extension.py
> +    #print dateBegin
Remove code in comments. There are many more, leftovers should be removed.

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/Extension.py
> +    tot=(dateEnd-dateBegin).days
Change you change it for `numberOfDays`?

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/Extension.py
> +    checkimg=check(myurl)
`check` _actually calls `requests.get(myurl)`, so you are calling the first image once, _without a timeout_, and then fetching it again two lines later with a timeout.

So in fact, you should remove `check` altogether.

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/Extension.py
> +    imagenr=int(document.get_meta_data_value('myrownr')[0])
You should handle the case where `myrownr` is undefined.

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/Extension.py
> +        return res.status_code
This return is useless.

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/PeopleMap.html
> +  <style>
Can this be put in its own CSS file?

& Alignment is very off for many of those rules.

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/PeopleMap.html
> +      var ResultsRelated = (function (_super) {
Was this compiled from TypeScript?

It would be very useful to have the original files.

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/PeopleMap.html
> +  <script>
Can this also be put in a separate file?

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/PeopleMap.html
> +            //                    this.normalCaption = Coveo.$('<div/>').addClass('coveo-folding-header-caption').text(this.options.normalCaption).appendTo(header);
Remove commented code, and the `if` before does nothing.

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/PeopleMap.html
> +          //.addClass('coveo-result-folding-child-result')
Commented code

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/PeopleMap.html
> +							//disable it
Both comments are "disable it"

2017-03-08 19:55 UTC, francoislg commented on ResourceLocator/PeopleMap.html
> +	//Coveo.$('#search').coveo('init');
Commented code

2017-03-09 08:44 UTC, wnijmeijer commented on ResourceLocator/Extension.py
> +        return res.status_code
done

2017-03-09 08:45 UTC, wnijmeijer commented on ResourceLocator/Extension.py
> +    #Field to store the availability in
done

2017-03-09 08:46 UTC, wnijmeijer commented on ResourceLocator/Extension.py
> +    dateEndP2=Date+datetime.timedelta(days=90+currenthours)
done

2017-03-09 08:46 UTC, wnijmeijer commented on ResourceLocator/Extension.py
> +    #print dateBegin
done

2017-03-09 08:47 UTC, wnijmeijer commented on ResourceLocator/Extension.py
> +    tot=(dateEnd-dateBegin).days
done

2017-03-09 08:49 UTC, wnijmeijer commented on ResourceLocator/Extension.py
> +    imagenr=int(document.get_meta_data_value('myrownr')[0])
myrownr is always there!

2017-03-09 08:49 UTC, wnijmeijer commented on ResourceLocator/Extension.py
> +    checkimg=check(myurl)
ok

2017-03-09 08:53 UTC, wnijmeijer commented on ResourceLocator/PeopleMap.html
> +      var ResultsRelated = (function (_super) {
no, this is created here.

2017-03-09 08:56 UTC, wnijmeijer commented on ResourceLocator/PeopleMap.html
> +  <script>
yes, but for the example i think it should stay here

2017-03-09 08:57 UTC, wnijmeijer commented on ResourceLocator/PeopleMap.html
> +            //                    this.normalCaption = Coveo.$('<div/>').addClass('coveo-folding-header-caption').text(this.options.normalCaption).appendTo(header);
done

2017-03-09 08:57 UTC, wnijmeijer commented on ResourceLocator/PeopleMap.html
> +          //.addClass('coveo-result-folding-child-result')
done

2017-03-09 08:58 UTC, wnijmeijer commented on ResourceLocator/PeopleMap.html
> +							//disable it
done

2017-03-09 08:58 UTC, wnijmeijer commented on ResourceLocator/PeopleMap.html
> +	//Coveo.$('#search').coveo('init');
done

2017-03-10 13:45 UTC, merged